### PR TITLE
Add GPT4 Turbo model

### PR DESCRIPTION
**Pull request by ronaldmannak**
Adds GPT4 Turbo model and makes it the default.
Fixed token count in unit tests

### CODE REVIEW

**Comment by btfranklin** [comment]
Thank you for the contribution. However, for a few different reasons, I am not going to incorporate these changes. Allow me to explain.

1. In my own tests with the GPT-4 Turbo Preview chat API (which is the one used in this PR), I have found that while the response is generated much more quickly, the accuracy of System Instruction following is measurably inferior. I hope this will improve as the model is iterated. However, for now, this certainly should not be a default model choice.
2. This is only a "preview" model, and so I don't feel it's appropriate for inclusion in CleverBird as a production model.
3. It is entirely possible to use GPT-4 Turbo Preview in CleverBird today by using the "specific" model identifier and providing the appropriate version string.

**Comment by ronaldmannak** [comment]
That's very reasonable and totally understand your point. How do you feel about Assistant? Assistant also works for 3.5Turbo (though retrieval only works on 4Turbo).

I'll continue working on the branch and add more of the new API to it.

**Comment by btfranklin** [comment]
I'm very interested in the possibilities of the Assistant API. I've been experimenting with it and reading the docs, and my initial impression is that it would be substantially enough different from the primary ChatThread data structure and DX in CleverBird to probably justify a new data structure that doesn't necessarily incorporate the existing ChatThread-centric types. My first priority is going to be to update and re-align the existing CleverBird API to the updated chat endpoints (such as the deprecation of "functions" for "tools", etc.) and once that's all stabilized, to look at whether it makes sense to expand into the Assistant API realm.

**Comment by ronaldmannak** [comment]
Sounds good!

**Pull request closed without merging**
